### ISSUE TITLE
Python/TensorFlow/Keras versions

### ISSUE THREAD

**Issue by abrichr** [yangarbiter/multilabel-learn#3]
Hello, thank you to the authors for making this available!

I wonder if anyone who is able to run this could please share what versions of Python, TensorFlow, and Keras they are using? I have tried with multiple different combinations and have not had any success. The errors I have encountered include:

- cannot import name 'tf_utils'
- No module named 'tensorflow.compat'
- tensorflow.python.eager.core._SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'input_2:0' shape=(None, 3, 6) dtype=float32>]

The travis-ci build is currently failing, and hasn't passed since Keras was added to the project.

Any suggestions would be appreciated.

Thank you!

**Comment by yangarbiter** [comment]
Sorry about this. Since this is a pretty old project, I don't remember the exact version of the packages.

Could you try tensorflow 1.13.1 with keras 2.2.4?

Sorry for the inconvenience.

**Comment by abrichr** [comment]
@yangarbiter thanks for the suggestion!

Your previous suggestion of tensorflow 1.14 and keras 2.3 worked with Python 3.7.

Regarding this being an old project, do you have any recommendations for newer/better approaches to multilabel classification?

Thanks again!

**Comment by yangarbiter** [comment]
I am actually not very sure about the SOTA of multilabel classification right now. Maybe a place to start would be looking at papers that cited our paper (https://scholar.google.com/scholar?cites=7577675817034321822&as_sdt=2005&sciodt=0,5&hl=en).
